apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kis6ae9fn-nodejs 
  janus-idp.io/tekton: kis6ae9fn-nodejs
  backstage.io/kubernetes-id: kis6ae9fn-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kis6ae9fn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml