apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kis6ae9fn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kis6ae9fn-nodejs 
  name: kis6ae9fn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kis6ae9fn-nodejs 
